# > pip install pre-commit
# > pre-commit run --all-files
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: jacoco
        name: Coverage
        entry: mvn clean test jacoco:report
        language: system
        pass_filenames: false
        always_run: true
