version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: local-redis-container
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
  mysql-server:
    image: mysql:9.3.0
    container_name: local-mysql-container
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-demo}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password} # Use environment variable or .env file
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password} # Use environment variable or .env file
    ports:
      - "${MYSQL_HOST_PORT:-3306}:3306"
